同步最新discourse_docker代码仓

diff --git a/discourse-setup b/discourse-setup
--- a/discourse-setup
+++ b/discourse-setup
@@ -257,7 +257,8 @@ scale_ram_and_cpu() {
     avail_cores=`sysctl hw.ncpu | awk '/hw.ncpu:/ {print $2}'`
   else
     avail_gb=$(check_linux_memory)
-    avail_cores=$((`awk '/cpu cores/ {print $4;exit}' /proc/cpuinfo`*`sort /proc/cpuinfo | uniq | grep -c "physical id"`))
+    threads_per_core=$(lscpu | awk 'BEGIN {FS=":"} /Thread\(s\) per core/ {print $2}')
+    avail_cores=$((`lscpu | awk '/^CPU\(s\)/ {print $2}'`*${threads_per_core}))
   fi
   echo "Found ${avail_gb}GB of memory and $avail_cores physical CPU cores"
 
@@ -343,32 +344,40 @@ check_port() {
 ## read a variable from the config file
 ##
 read_config() {
-  config_line=`egrep "^  #?$1:" $web_file`
+  config_line=`grep -E "^  #?$1:" $web_file`
   read_config_result=`echo $config_line | awk  -F":" '{print $2}'`
   read_config_result=`echo $read_config_result | sed "s/^\([\"']\)\(.*\)\1\$/\2/g"`
 }
 
 read_default() {
-  config_line=`egrep "^  #?$1:" samples/standalone.yml`
+  config_line=`grep -E "^  #?$1:" samples/standalone.yml`
   read_default_result=`echo $config_line | awk  -F":" '{print $2}'`
   read_default_result=`echo $read_config_result | sed "s/^\([\"']\)\(.*\)\1\$/\2/g"`
 }
 
-assert_maxmind_license_key() {
+assert_maxmind_envs() {
   if  ! grep DISCOURSE_MAXMIND_LICENSE_KEY $web_file >/dev/null 2>&1
   then
-    echo "Adding MAXMIND placeholder to $web_file"
+    echo "Adding MAXMIND_LICENSE_KEY placeholder to $web_file"
     sed -i '/^.*LETSENCRYPT_ACCOUNT_EMAIL.*/a \ \ #DISCOURSE_MAXMIND_LICENSE_KEY: 1234567890123456' $web_file
   fi
-  if  ! grep DISCOURSE_MAXMIND_LICENSE_KEY $web_file >/dev/null 2>&1
+
+  if  ! grep DISCOURSE_MAXMIND_ACCOUNT_ID $web_file >/dev/null 2>&1
+  then
+    echo "Adding MAXMIND_ACCOUNT_ID placeholder to $web_file"
+    sed -i '/^.*LETSENCRYPT_ACCOUNT_EMAIL.*/a \ \ #DISCOURSE_MAXMIND_ACCOUNT_ID: 123456' $web_file
+  fi
+
+
+  if ! grep -e DISCOURSE_MAXMIND_LICENSE_KEY -e DISCOURSE_MAXMIND_ACCOUNT_ID $web_file >/dev/null 2>&1
   then
     cat <<EOF
 
-    Adding DISCOURSE_MAXMIND_LICENSE_KEY to $web_file has failed! This
-    indicates either that your $web_file is very old or otherwise not
-    what the script expects or that there is a bug in this script. The
-    best solution for a novice is to delete $web_file and start over.
-    An expert might prefer to edit $web_file by hand.
+    Adding DISCOURSE_MAXMIND_ACCOUNT_ID and DISCOURSE_MAXMIND_LICENSE_KEY to
+    $web_file has failed! This indicates either that your $web_file is very
+    old or otherwise not what the script expects or that there is a bug in
+    this script. The best solution for a novice is to delete $web_file and
+    start over. An expert might prefer to edit $web_file by hand.
 
 EOF
     read -p "Press return to continue or control-c to quit..."
@@ -440,14 +449,14 @@ ask_user_for_config() {
   local smtp_port=$read_config_result
   read_config "DISCOURSE_SMTP_USER_NAME"
   local smtp_user_name=$read_config_result
-  if [ "$smtp_password" = "pa$$word" ]
+  if [ "$smtp_password" = "pa\$\$word" ]
   then
-    smtp_password = ""
+    smtp_password=""
   fi
   read_config "DISCOURSE_NOTIFICATION_EMAIL"
   local notification_email=$read_config_result
   read_config "DISCOURSE_SMTP_DOMAIN"
-  local discourse_smtp_DOMAIN=$read_config_result
+  local discourse_smtp_domain=$read_config_result
 
   read_config "LETSENCRYPT_ACCOUNT_EMAIL"
   local letsencrypt_account_email=$read_config_result
@@ -462,15 +471,23 @@ ask_user_for_config() {
     local letsencrypt_status="Enter 'OFF' to disable."
   fi
 
+  read_config "DISCOURSE_MAXMIND_ACCOUNT_ID"
+  local maxmind_account_id=$read_config_result
+  if [ -z $maxmind_account_id ]
+  then
+    maxmind_account_id="123456"
+  fi
+
+  if [ "$maxmind_account_id" == "123456" ]
+  then
+    local maxmind_status="ENTER to continue without MAXMIND GeoLite2 geolocation database"
+  fi
+
   read_config "DISCOURSE_MAXMIND_LICENSE_KEY"
   local maxmind_license_key=$read_config_result
   if [ -z $maxmind_license_key ]
   then
     maxmind_license_key="1234567890123456"
-  fi
-  if [ "$maxmind_license_key" == "1234567890123456" ]
-  then
-    local maxmind_status="ENTER to continue without MAXMIND GeoLite2 geolocation database"
   fi
 
   local new_value=""
@@ -547,7 +564,7 @@ ask_user_for_config() {
     then
       if [ "$smtp_address" == "smtp.sparkpostmail.com" ]
       then
-      	smtp_user_name="SMTP_Injection"
+        smtp_user_name="SMTP_Injection"
       fi
       if [ "$smtp_address" == "smtp.sendgrid.net" ]
       then
@@ -586,7 +603,9 @@ ask_user_for_config() {
     fi
 
     # set smtp_domain default value here rather than use Rails default of localhost
-    smtp_domain=$(echo $notification_email | sed -e "s/.*@//")
+    default_smtp_domain=${notification_email#*@}
+    # if DISCOURSE_SMTP_DOMAIN is in the config use that instead
+    smtp_domain=${discourse_smtp_domain:-${default_smtp_domain}}
 
     if [ ! -z $letsencrypt_account_email ]
     then
@@ -603,12 +622,21 @@ ask_user_for_config() {
       fi
     fi
 
-    read_config "DISCOURSE_MAXMIND_LICENSE_KEY"
-    local maxmind_license_key=$read_config_result
-    read -p "Optional Maxmind License key ($maxmind_status) [$maxmind_license_key]: " new_value
+    read_config "DISCOURSE_MAXMIND_ACCOUNT_ID"
+    local maxmind_account_id=$read_config_result
+    read -p "Optional MaxMind Account ID ($maxmind_status) [$maxmind_account_id]: " new_value
     if [ ! -z "$new_value" ]
     then
-      maxmind_license_key="$new_value"
+      maxmind_account_id="$new_value"
+
+      read_config "DISCOURSE_MAXMIND_LICENSE_KEY"
+      local maxmind_license_key=$read_config_result
+      read -p "MaxMind License key [$maxmind_license_key]: " new_value
+
+      if [ ! -z "$new_value" ]
+      then
+        maxmind_license_key="$new_value"
+      fi
     fi
 
     echo -e "\nDoes this look right?\n"
@@ -625,11 +653,18 @@ ask_user_for_config() {
       echo "Let's Encrypt : $letsencrypt_account_email"
     fi
 
+    if [ "$maxmind_account_id" != "123456" ]
+    then
+      echo "MaxMind account ID: $maxmind_account_id"
+    else
+      echo "MaxMind account ID: (unset)"
+    fi
+
     if [ "$maxmind_license_key" != "1234567890123456" ]
     then
-      echo "Maxmind license: $maxmind_license_key"
+      echo "MaxMind license key: $maxmind_license_key"
     else
-      echo "Maxmind license: (unset)"
+      echo "MaxMind license key: (unset)"
     fi
 
     echo ""
@@ -716,8 +751,8 @@ ask_user_for_config() {
          then
            SLASH="Q"
            if [[ "$smtp_password" == *"$SLASH"* ]]
-	   then
-	     SLASH="BROKEN"
+           then
+             SLASH="BROKEN"
              echo "========================================"
              echo "WARNING!!!"
              echo "Your password contains all available delimiters (+, |, and Q). "
@@ -779,6 +814,19 @@ ask_user_for_config() {
   fi
 
   echo
+
+  if [ $maxmind_account_id != "123456" ]
+  then
+    sed -i -e "s/^.*DISCOURSE_MAXMIND_ACCOUNT_ID:.*/  DISCOURSE_MAXMIND_ACCOUNT_ID: $maxmind_account_id/w $changelog" $web_file
+    if [ -s $changelog ]
+    then
+      rm $changelog
+    else
+      echo "DISCOURSE_MAXMIND_ACCOUNT_ID change failed."
+      update_ok="n"
+    fi
+  fi
+
   if [ $maxmind_license_key != "1234567890123456" ]
   then
     sed -i -e "s/^.*DISCOURSE_MAXMIND_LICENSE_KEY:.*/  DISCOURSE_MAXMIND_LICENSE_KEY: $maxmind_license_key/w $changelog" $web_file
@@ -888,11 +936,11 @@ then
   then
     echo "Stopping existing container in 5 seconds or Control-C to cancel."
     sleep 5
+    ./launcher stop $app_name
   else
     echo "DEBUG MODE ON. Not stopping the container."
   fi
-  ./launcher stop $app_name
-  assert_maxmind_license_key
+  assert_maxmind_envs
   assert_notification_email
   assert_smtp_domain
   echo
