FEATURE: Make launcher forgive swapped parameters

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -20,8 +20,25 @@ usage () {
   exit 1
 }
 
-command=$1
-config=$2
+commands_re='(start|stop|restart|destroy|enter|logs|bootstrap|rebuild|cleanup)'
+if [[ $1 =~ $commands_re ]]; then
+  command=$1
+  config=$2
+else
+  if [[ $2 =~ $commands_re ]]; then
+    command=$2
+    config=$1
+    echo
+    echo "WARNING: The correct usage is 'launcher $command $config' rather than 'launcher $config $command'."
+    echo
+  else
+    echo
+    echo "ERROR: '$1' is not a correct command: $commands_re"
+    echo
+    exit 1;
+  fi
+fi
+
 user_args=""
 
 while [ ${#} -gt 0 ]; do
@@ -644,7 +661,7 @@ case "$command" in
         elif [ $LOCAL = $BASE ]; then
           echo "Updating Launcher"
           git pull || (echo 'failed to update' && exit 1)
-          
+
           for (( i=${#BASH_ARGV[@]}-1,j=0; i>=0,j<${#BASH_ARGV[@]}; i--,j++ ))
           do
             args[$j]=${BASH_ARGV[$i]}
