FIX: have "rebuild" update discourse docker

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -432,6 +432,8 @@ case "$command" in
       ;;
 
   rebuild)
+      echo "Updating discourse docker"
+      git pull || (echo 'failed to update' && exit 1)
       if [ -e $cidfile ]
         then
           echo "Stopping old container"
