FEATURE: Update base image and set default to postgresql 15 (#909)
This updates the default PostgreSQL version to 15.

  * image/base: update default postgres version to 15
  * launcher: bump base image to include postgres 15
  * postgres.template.yml: update default version to 15
  * postgres.15.template.yml: current version template

Legacy version templates:

  * postgres.13.template.yml
  * postgres.12.template.yml
  * postgres.10.template.yml
  * postgres.9.5.template.yml

diff --git a/templates/postgres.template.yml b/templates/postgres.template.yml
--- a/templates/postgres.template.yml
+++ b/templates/postgres.template.yml
@@ -28,7 +28,7 @@ run:
      contents: |
         #!/bin/sh
         exec 2>&1
-        HOME=/var/lib/postgresql USER=postgres exec thpoff chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/13/bin/postmaster -D /etc/postgresql/13/main
+        HOME=/var/lib/postgresql USER=postgres exec thpoff chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/15/bin/postmaster -D /etc/postgresql/15/main
 
   - file:
      path: /etc/service/postgres/log/run
@@ -62,15 +62,18 @@ run:
         fi
         rm -fr /shared/postgres_run/.s*
         rm -fr /shared/postgres_run/*.pid
-        mkdir -p /shared/postgres_run/13-main.pg_stat_tmp
-        chown postgres:postgres /shared/postgres_run/13-main.pg_stat_tmp
-        chown -R root /var/lib/postgresql/13/main
-        [ ! -e /shared/postgres_data ] && install -d -m 0755 -o postgres -g postgres /shared/postgres_data && sudo -E -u postgres /usr/lib/postgresql/13/bin/initdb -D /shared/postgres_data || exit 0
-        chown -R postgres:postgres /shared/postgres_data
-        chown -R postgres:postgres /var/run/postgresql
-        if [ -f /root/upgrade_postgres ]; then
-          /root/upgrade_postgres
-          rm /root/upgrade_postgres
+        mkdir -p /shared/postgres_run/15-main.pg_stat_tmp
+        chown postgres:postgres /shared/postgres_run/15-main.pg_stat_tmp
+        chown -R root /var/lib/postgresql/15/main
+        if [ ! -e /shared/postgres_data ]; then
+          install -d -m 0755 -o postgres -g postgres /shared/postgres_data
+          sudo -E -u postgres /usr/lib/postgresql/15/bin/initdb -D /shared/postgres_data
+          chown -R postgres:postgres /shared/postgres_data
+          chown -R postgres:postgres /var/run/postgresql
+        elif [ -f /root/upgrade_postgres ]; then
+          unset RETCODE
+          /root/upgrade_postgres || RETCODE=$?
+          [ -z "${RETCODE}" ] && rm /root/upgrade_postgres || exit $RETCODE
         fi
         # Necessary to enable backups
         install -d -m 0755 -o postgres -g postgres /shared/postgres_backup
@@ -82,17 +85,22 @@ run:
        #!/bin/bash
        PG_MAJOR_OLD=`cat /shared/postgres_data/PG_VERSION`
 
-       if [ ! "13" = "$PG_MAJOR_OLD" ]; then
-         echo Upgrading PostgreSQL from version ${PG_MAJOR_OLD} to 13
+       if [ ! "15" = "$PG_MAJOR_OLD" ]; then
+         echo Upgrading PostgreSQL from version ${PG_MAJOR_OLD} to 15
          free_disk=$(df -P -B1 /shared | tail -n 1 | awk '{print $4}')
          required=$(($(du -sb /shared/postgres_data | awk '{print $1}') * 2))
 
          if [ "$free_disk" -lt "$required" ]; then
-          echo "WARNING: Upgrading PostgreSQL would require an additional $(numfmt --to=si $(($required - $free_disk))) of disk space"
-          echo "Please free up some space, or expand your disk, before continuing."
-          echo ''
-          echo 'To avoid upgrading change "templates/postgres.template.yml" TO "templates/postgres.12.template.yml" in containers/app.yml'
-          exit 1
+           echo
+           echo -------------------------------------------------------------------------------------
+           echo "WARNING: Upgrading PostgreSQL would require an additional $(numfmt --to=si $(($required - $free_disk))) of disk space"
+           echo "Please free up some space, or expand your disk, before continuing."
+           echo
+           echo 'To avoid upgrading change "templates/postgres.template.yml" TO "templates/postgres.13.template.yml" in containers/app.yml'
+           echo
+           echo 'You can run "./launcher start app" to restart your app in the meanwhile.'
+           echo -------------------------------------------------------------------------------------
+           exit 1
          fi
 
          if [ -d /shared/postgres_data_old ]; then
@@ -100,10 +108,10 @@ run:
          fi
 
          rm -fr /shared/postgres_data_new
-         install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/13/bin/initdb -D /shared/postgres_data_new || exit 0
+         install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/15/bin/initdb -D /shared/postgres_data_new || exit 0
          apt-get update
          apt-get install -y postgresql-${PG_MAJOR_OLD}
-         chown -R postgres:postgres /var/lib/postgresql/13
+         chown -R postgres:postgres /var/lib/postgresql/15
          /etc/init.d/postgresql stop
          rm -fr /shared/postgres_data/postmaster.pid
          cd ~postgres
@@ -111,16 +119,16 @@ run:
          echo  >> /shared/postgres_data/postgresql.conf
          echo "data_directory = '/shared/postgres_data'" >> /shared/postgres_data/postgresql.conf
          SUCCESS=true
-         sudo -u postgres /usr/lib/postgresql/13/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/13/bin || SUCCESS=false
+         sudo -u postgres /usr/lib/postgresql/15/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/15/bin || SUCCESS=false
 
          if [[ "$SUCCESS" == 'false' ]]; then
            echo -------------------------------------------------------------------------------------
            echo UPGRADE OF POSTGRES FAILED
            echo
-           echo Please visit https://meta.discourse.org/t/postgresql-13-update/172563 for support.
+           echo Please visit https://meta.discourse.org/t/postgresql-15-update/349515 for support.
            echo
            echo You can run "./launcher start app" to restart your app in the meanwhile
-           echo
+           echo -------------------------------------------------------------------------------------
            exit 1
          fi
 
@@ -141,69 +149,69 @@ run:
        fi
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
-      from: "data_directory = '/var/lib/postgresql/13/main'"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
+      from: "data_directory = '/var/lib/postgresql/15/main'"
       to: "data_directory = '/shared/postgres_data'"
 
   # listen on all interfaces
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?listen_addresses *=.*/
       to: "listen_addresses = '*'"
 
   # sync commit off is faster and less spiky, also marginally less safe
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?synchronous_commit *=.*/
       to: "synchronous_commit = $db_synchronous_commit"
 
   # default is 128MB which is way too small
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?shared_buffers *=.*/
       to: "shared_buffers = $db_shared_buffers"
 
   # default is 1MB which is too small
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?work_mem *=.*/
       to: "work_mem = $db_work_mem"
 
   # allow for other
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?default_text_search_config *=.*/
       to: "default_text_search_config = '$db_default_text_search_config'"
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?checkpoint_segments *=.*/
       to: "checkpoint_segments = $db_checkpoint_segments"
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?logging_collector *=.*/
       to: "logging_collector = $db_logging_collector"
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?log_min_duration_statement *=.*/
       to: "log_min_duration_statement = $db_log_min_duration_statement"
 
   - replace:
-      filename: "/etc/postgresql/13/main/pg_hba.conf"
+      filename: "/etc/postgresql/15/main/pg_hba.conf"
       from: /^#local +replication +postgres +peer$/
       to: "local replication postgres  peer"
 
-  # allow all to connect in with md5 auth
+  # allow all to connect in with md5/scram auth
   - replace:
-      filename: "/etc/postgresql/13/main/pg_hba.conf"
+      filename: "/etc/postgresql/15/main/pg_hba.conf"
       from: /^host.*all.*all.*127.*$/
       to: "host all all 0.0.0.0/0 md5"
 
-  # allow all to connect in with md5 auth (IPv6)
+  # allow all to connect in with md5/scram auth (IPv6)
   - replace:
-      filename: "/etc/postgresql/13/main/pg_hba.conf"
+      filename: "/etc/postgresql/15/main/pg_hba.conf"
       from: /^host.*all.*all.*::1\/128.*$/
       to: "host all all ::/0 md5"
 
@@ -221,7 +229,7 @@ run:
       background: true
       # use fast shutdown for pg
       stop_signal: INT
-      cmd: HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/13/bin/postmaster -D /etc/postgresql/13/main
+      cmd: HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/15/bin/postmaster -D /etc/postgresql/15/main
 
   - file:
       path: /usr/local/bin/create_db
