Finish bumping base image to 2.0.20260116-2039
Followup to ddac3562c0dfe2563e7076d0a16d09dd48c86d15

diff --git a/templates/postgres.template.yml b/templates/postgres.template.yml
--- a/templates/postgres.template.yml
+++ b/templates/postgres.template.yml
@@ -1,4 +1,4 @@
-base_image: discourse/base:2.0.20260109-0020
+base_image: discourse/base:2.0.20260116-2039
 params:
   db_synchronous_commit: "off"
   db_shared_buffers: "256MB"
@@ -13,16 +13,16 @@ params:
 hooks:
   before_code:
     - replace:
-       filename: /etc/service/unicorn/run
-       from: "# postgres"
-       to: |
-         sv start postgres || exit 1
+        filename: /etc/service/unicorn/run
+        from: "# postgres"
+        to: |
+          sv start postgres || exit 1
 
 run:
   - file:
-     path: /etc/service/postgres/run
-     chmod: "+x"
-     contents: |
+      path: /etc/service/postgres/run
+      chmod: "+x"
+      contents: |
         #!/bin/sh
         exec 2>&1
         if [ -f /root/install_postgres ]; then
@@ -37,19 +37,19 @@ run:
         HOME=/var/lib/postgresql USER=postgres exec thpoff chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/15/bin/postmaster -D /etc/postgresql/15/main
 
   - file:
-     path: /etc/service/postgres/log/run
-     chmod: "+x"
-     contents: |
-       #!/bin/sh
-       mkdir -p /var/log/postgres
-       exec svlogd /var/log/postgres
+      path: /etc/service/postgres/log/run
+      chmod: "+x"
+      contents: |
+        #!/bin/sh
+        mkdir -p /var/log/postgres
+        exec svlogd /var/log/postgres
 
   - file:
-     path: /etc/runit/3.d/99-postgres
-     chmod: "+x"
-     contents: |
-       #!/bin/bash
-       sv stop postgres
+      path: /etc/runit/3.d/99-postgres
+      chmod: "+x"
+      contents: |
+        #!/bin/bash
+        sv stop postgres
 
   - file:
       path: /root/install_postgres
@@ -90,77 +90,77 @@ run:
         install -d -m 0755 -o postgres -g postgres /shared/postgres_backup
 
   - file:
-     path: /root/upgrade_postgres
-     chmod: "+x"
-     contents: |
-       #!/bin/bash
-       PG_MAJOR_OLD=`cat /shared/postgres_data/PG_VERSION`
+      path: /root/upgrade_postgres
+      chmod: "+x"
+      contents: |
+        #!/bin/bash
+        PG_MAJOR_OLD=`cat /shared/postgres_data/PG_VERSION`
 
-       if [ ! "15" = "$PG_MAJOR_OLD" ]; then
-         echo Upgrading PostgreSQL from version ${PG_MAJOR_OLD} to 15
-         free_disk=$(df -P -B1 /shared | tail -n 1 | awk '{print $4}')
-         required=$(($(du -sb /shared/postgres_data | awk '{print $1}') * 2))
+        if [ ! "15" = "$PG_MAJOR_OLD" ]; then
+          echo Upgrading PostgreSQL from version ${PG_MAJOR_OLD} to 15
+          free_disk=$(df -P -B1 /shared | tail -n 1 | awk '{print $4}')
+          required=$(($(du -sb /shared/postgres_data | awk '{print $1}') * 2))
 
-         if [ "$free_disk" -lt "$required" ]; then
-           echo
-           echo -------------------------------------------------------------------------------------
-           echo "WARNING: Upgrading PostgreSQL would require an additional $(numfmt --to=si $(($required - $free_disk))) of disk space"
-           echo "Please free up some space, or expand your disk, before continuing."
-           echo
-           echo 'To avoid upgrading change "templates/postgres.template.yml" TO "templates/postgres.13.template.yml" in containers/app.yml'
-           echo
-           echo 'You can run "./launcher start app" to restart your app in the meanwhile.'
-           echo -------------------------------------------------------------------------------------
-           exit 1
-         fi
+          if [ "$free_disk" -lt "$required" ]; then
+            echo
+            echo -------------------------------------------------------------------------------------
+            echo "WARNING: Upgrading PostgreSQL would require an additional $(numfmt --to=si $(($required - $free_disk))) of disk space"
+            echo "Please free up some space, or expand your disk, before continuing."
+            echo
+            echo 'To avoid upgrading change "templates/postgres.template.yml" TO "templates/postgres.13.template.yml" in containers/app.yml'
+            echo
+            echo 'You can run "./launcher start app" to restart your app in the meanwhile.'
+            echo -------------------------------------------------------------------------------------
+            exit 1
+          fi
 
-         if [ -d /shared/postgres_data_old ]; then
-           mv /shared/postgres_data_old /shared/postgres_data_older
-         fi
+          if [ -d /shared/postgres_data_old ]; then
+            mv /shared/postgres_data_old /shared/postgres_data_older
+          fi
 
-         rm -fr /shared/postgres_data_new
-         install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/15/bin/initdb -D /shared/postgres_data_new || exit 0
-         apt-get update
-         apt-get install -y postgresql-${PG_MAJOR_OLD} postgresql-${PG_MAJOR_OLD}-pgvector
-         pg_createcluster -u postgres --no-status ${PG_MAJOR_OLD} main
-         chown -R postgres:postgres /var/lib/postgresql/15
-         /etc/init.d/postgresql stop
-         rm -fr /shared/postgres_data/postmaster.pid
-         cd ~postgres
-         cp -pr /etc/postgresql/${PG_MAJOR_OLD}/main/* /shared/postgres_data
-         echo  >> /shared/postgres_data/postgresql.conf
-         echo "data_directory = '/shared/postgres_data'" >> /shared/postgres_data/postgresql.conf
-         SUCCESS=true
-         sudo -u postgres /usr/lib/postgresql/15/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/15/bin || SUCCESS=false
+          rm -fr /shared/postgres_data_new
+          install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/15/bin/initdb -D /shared/postgres_data_new || exit 0
+          apt-get update
+          apt-get install -y postgresql-${PG_MAJOR_OLD} postgresql-${PG_MAJOR_OLD}-pgvector
+          pg_createcluster -u postgres --no-status ${PG_MAJOR_OLD} main
+          chown -R postgres:postgres /var/lib/postgresql/15
+          /etc/init.d/postgresql stop
+          rm -fr /shared/postgres_data/postmaster.pid
+          cd ~postgres
+          cp -pr /etc/postgresql/${PG_MAJOR_OLD}/main/* /shared/postgres_data
+          echo  >> /shared/postgres_data/postgresql.conf
+          echo "data_directory = '/shared/postgres_data'" >> /shared/postgres_data/postgresql.conf
+          SUCCESS=true
+          sudo -u postgres /usr/lib/postgresql/15/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/15/bin || SUCCESS=false
 
-         if [[ "$SUCCESS" == 'false' ]]; then
-           echo -------------------------------------------------------------------------------------
-           echo UPGRADE OF POSTGRES FAILED
-           echo
-           echo Please visit https://meta.discourse.org/t/postgresql-15-update/349515 for support.
-           echo
-           echo You can run "./launcher start app" to restart your app in the meanwhile
-           echo -------------------------------------------------------------------------------------
-           exit 1
-         fi
+          if [[ "$SUCCESS" == 'false' ]]; then
+            echo -------------------------------------------------------------------------------------
+            echo UPGRADE OF POSTGRES FAILED
+            echo
+            echo Please visit https://meta.discourse.org/t/postgresql-15-update/349515 for support.
+            echo
+            echo You can run "./launcher start app" to restart your app in the meanwhile
+            echo -------------------------------------------------------------------------------------
+            exit 1
+          fi
 
-         mkdir /shared/postgres_data_old
-         mv /shared/postgres_data/* /shared/postgres_data_old
-         mv /shared/postgres_data_new/* /shared/postgres_data
-         rmdir /shared/postgres_data_new
+          mkdir /shared/postgres_data_old
+          mv /shared/postgres_data/* /shared/postgres_data_old
+          mv /shared/postgres_data_new/* /shared/postgres_data
+          rmdir /shared/postgres_data_new
 
-         echo -------------------------------------------------------------------------------------
-         echo UPGRADE OF POSTGRES COMPLETE
-         echo
-         echo Old ${PG_MAJOR_OLD} database is stored at /shared/postgres_data_old
-         echo
-         echo To complete the upgrade, rebuild again using:
-         echo
-         echo     ./launcher rebuild app
-         echo -------------------------------------------------------------------------------------
-         # Magic exit status to denote no failure
-         exit 77
-       fi
+          echo -------------------------------------------------------------------------------------
+          echo UPGRADE OF POSTGRES COMPLETE
+          echo
+          echo Old ${PG_MAJOR_OLD} database is stored at /shared/postgres_data_old
+          echo
+          echo To complete the upgrade, rebuild again using:
+          echo
+          echo     ./launcher rebuild app
+          echo -------------------------------------------------------------------------------------
+          # Magic exit status to denote no failure
+          exit 77
+        fi
 
   - replace:
       filename: "/etc/postgresql/15/main/postgresql.conf"
@@ -268,10 +268,10 @@ run:
         fi
 
   - file:
-     path: /var/lib/postgresql/take-database-backup
-     chown: postgres:postgres
-     chmod: "+x"
-     contents: |
+      path: /var/lib/postgresql/take-database-backup
+      chown: postgres:postgres
+      chmod: "+x"
+      contents: |
         #!/bin/bash
         ID=db-$(date +%F_%T)
         FILENAME=/shared/postgres_backup/$ID.tar.gz
@@ -279,8 +279,8 @@ run:
         echo $FILENAME
 
   - file:
-     path: /var/spool/cron/crontabs/postgres
-     contents: |
+      path: /var/spool/cron/crontabs/postgres
+      contents: |
         # m h  dom mon dow   command
         #MAILTO=?
         #0 */4 * * * /var/lib/postgresql/take-database-backup
